### ISSUE TITLE
セッションの詳細ダイアログが画面内に収まらないことがある

### ISSUE THREAD

**Issue by youkinjoh** [webrtc-conference-jp/webrtc-conference-jp.github.io#68]
「WebRTCがビデオ会議システム市場に与えるインパクトを探る」のセッション詳細が
大きめのモニタで見ても画面内に収まっていない。
また、ブラウザの表示領域よりもセッション詳細のダイアログが大きい場合、
上下方法がセンタリングされず、上1/3程しか画面内に入らない。

**Comment by youkinjoh** [comment]
再現方法
 * ウィンドウサイズを小さめにする
 * http://webrtcconference.jp/session/ を読み込む
 * 「WebRTCがビデオ会議システム市場に与えるインパクトを探る」をクリック

ただ、以下のようにすると画面内に収まります。
修正方法のヒントになるかも...。
 * ウィンドウサイズを大きくする
 * http://webrtcconference.jp/session/ を読み込む
 * 「WebRTCがビデオ会議システム市場に与えるインパクトを探る」をクリック
 * セッション詳細を表示したままウィンドウサイズを小さくする
 * セッション詳細を閉じる
 * 再度「WebRTCがビデオ会議システム市場に与えるインパクトを探る」をクリック

**Comment by youkinjoh** [comment]
`.detail_item` に
```
max-height: 480px;
overflow-y: scroll;
```
を追加するとそれなりの表示にはなりました。

**Comment by youkinjoh** [comment]
https://github.com/webrtc-conference-jp/webrtc-conference-jp.github.io/issues/68#issuecomment-69166254 の方法だと
「講演者」と「所属・肩書」が縦になってしまいました...。
`.detail_base_item` の `width` を `400px` に変更すると横に表示されるようになりますが、
他に影響が出てしまうかもしれません...。

**Comment by shumpei** [comment]
ご指摘ありがとうございます！

max-height: 480px;
overflow-y: scroll;

ぼくの環境だと良さそうに見えます。
講演者と所属肩書が縦になる、って現象がむしろ再現できないかも。

ちょっと今日打合せが立て込んでいて、対応する時間が取れないので、まずはmax-height: 480pxで逃げておきたい気がしているのですが、まずいでしょうか？

**Comment by youkinjoh** [comment]
とりあえずの対応でしたら
```
max-height: 480px;
overflow-y: scroll;
```
で大丈夫だと思います。

**Comment by youkinjoh** [comment]
`#detail_context` 配下がかなりキッカリと幅指定されているのですが、
`overflow-y: scroll;` を指定してスクロールバーが表示されることで、
内包している `.detail_base_item` の表示幅が足りなくなって
折り返されているのが原因のようです。

**Comment by youkinjoh** [comment]
「講演者」と「所属・肩書」が縦になったときのスクリーンショットです。

![detail](https://cloud.githubusercontent.com/assets/2393395/5675311/6ca598a6-97fe-11e4-9c9b-866f1a810ef3.png)

**Comment by shumpei** [comment]
おお、ありがとうございます。
でも正直、縦並びになっても問題ないような…

**Comment by youkinjoh** [comment]
右がスカスカなのに、長い「所属・肩書」が折り返されていているのがモヤッとしてますw
max-heightで高さ制限しているので一見できる情報量が少なくなっているのも気になりますね。

多分、以下の方法で再現できると思います。
 * 「システム環境設定」→「一般」→「スクロールバーの表示」の「常に表示」をチェック

あと、Windowsだとスクロールバーを消す設定はなかったはずで、
そうなると横に表示されるのは
「OS Xを使いつつスクロールバーを常に表示にしていない」場合のみで
多くの環境で縦に表示されていると思います。

まあ 「そういうデザインと言い切る」とか
「個人の好みとか」そういう問題になりそうなのでお任せします!

**Comment by shumpei** [comment]
@youkinjoh さんありがとうございます。
環境設定を変更して、再現することが出来ました。
以前頂いた「.detail_base_item の width を 400px に変更する」という解決策に加え、.detail_base_item以下の項目の幅を色々調整して、折り返し表示を抑制しました。
